### ISSUE TITLE
Is not Stabilimento balneare 

### ISSUE THREAD

**Issue by lampaDario1543** [kev1nl1u/StabilimentoBalneare#1]

**Comment by kev1nl1u** [comment]
Read the readme. It is clearly stated:
`The current version is updated to manage an ice rink for the winter`
Closing this issue because it was not an issue to begin with.
Read the readme.
![zupeb](https://github.com/user-attachments/assets/cd5163c8-87fb-46a8-a4d5-d4753d1ba93c)

😡😡💀👺👺👽🤬🤬😤😤💢👿
